Augh.  Fix the Qt bundles for yosemite.

diff --git a/packaging/macos/build-mac b/packaging/macos/build-mac
--- a/packaging/macos/build-mac
+++ b/packaging/macos/build-mac
@@ -54,12 +54,38 @@ make
 make test ARGS=-V
 make install
 
-echo 'Adding missing Info.plist files to Qt for code signing...'
+# Clean up the Qt bundles, which are not laid out correctly.
 for i in QtCore QtGui; do
-  infodir="$DEST/Regina.app/Contents/Frameworks/$i.framework/Resources/"
-  if [ ! -e "$infodir" ]; then
-    mkdir "$infodir"
+  fwdir="$DEST/Regina.app/Contents/Frameworks/$i.framework"
+  resdir="$fwdir/Versions/4/Resources"
+
+  if [ -e "$resdir" ]; then
+    echo "ERROR: versioned Resources directory already exists."
+    exit 1
   fi
-  cp -v /Library/Frameworks/$i.framework/Contents/Info.plist "$infodir"
+  if [ -d "$fwdir/Resources" ]; then
+    echo "$i: moving Resources/ into versioned framework directory..."
+    mv "$fwdir/Resources" "$resdir"
+  else
+    echo "$i: creating versioned Resources directory..."
+    mkdir "$resdir"
+  fi
+
+  echo "$i: adding missing Info.plist file to framework..."
+  cp /Library/Frameworks/$i.framework/Contents/Info.plist "$resdir"
+
+  if [ -e "$fwdir/Versions/Current" ]; then
+    echo "ERROR: Current symlink already exists."
+    exit 1
+  fi
+
+  echo "$i: setting up symlinks..."
+  ( cd "$fwdir/Versions" ; ln -s 4 Current )
+  ( cd "$fwdir" ; ln -s Versions/Current/Resources Resources )
+
+  if ( grep _debug "$fwdir/Resources/Info.plist" >/dev/null ); then
+    echo "$i: unbreaking Info.plist"
+    sed -i -e 's/_debug//' "$fwdir/Resources/Info.plist"
+  fi
 done
 
